easy_admin:
   site_name: "SUP'Votes"
   entities:
       Election:
         class: App\Entity\Election
         list:
          fields: ['id','start','endduration','localisation','candidateElection','users']
         form:
          fields:
             - 'start'
             - 'endduration'
             - 'localisation'
             - 'candidateElection'
             -   property: 'users'
                 type: 'entity'
                 type_options:
                     multiple: true
                     class: 'App\Entity\User'
                     by_reference: false
             # - { property: 'rol
       Candidate:
         class: App\Entity\Candidate
         list:
          fields: ['id','stylesheet','elections','userRelated','informations','scores']
         form:
          fields:
             - 'stylesheet'
             - 'userRelated'
             - 'scores'
             - { property: 'informations', type: 'App\Form\Type\JsonType' }
             -   property: 'elections'
                 type: 'entity'
                 type_options:
                     multiple: true
                     class: 'App\Entity\Election'
                     by_reference: false
       User:
         class: App\Entity\User
         form:
            fields:
               - { property: 'email' }
               - { property: 'password' }
               - { property: 'is_enable' }
               - { property: 'token' }
               - { property: 'roles', type: 'choice', type_options: { expanded: true, multiple: true, choices: { 'ROLE_USER': 'Normal user', 'ROLE_ADMIN': 'Administrator' } } }
       Score:
         class: App\Entity\Score