fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: UserBundle\Entity\User
    from_email:
        address: "samuel.simonney@gmail.com"
        sender_name: "samuel.simonney@gmail.com"